/* ==============================================================
   BANCO DE QUESTÕES DO SIMULADO (edite aqui)
   Questões originais no estilo da prova CCNA 200-301.
   As funções que usam este arquivo ficam em js/treinos.js.

   Campos de cada questão
   - id:         identificador único (ex.: "itn-01")
   - curso:      "ITN", "SRWE" ou "ENSA"
   - topico:     tópico do exame (use um dos nomes de TOPICOS, abaixo)
   - tipo:       "unica"    -> uma resposta certa
                 "multipla" -> várias respostas certas ("Escolha duas.")
                 "associar" -> ligar cada item ao alvo certo
   - enunciado:  texto da pergunta
   - exibicao:   (opcional) saída de comando ou topologia em texto
   - pkt:        (opcional) caminho de um arquivo do Packet Tracer
                 que você criou, ex.: "exercicios/vlan-falha.pkt"
   - explicacao: aparece depois da resposta

   Para "unica" e "multipla":
   - opcoes:     lista de textos
   - certas:     índices das opções certas (a primeira opção é 0)

   Para "associar":
   - alvos:      lista de destinos (aparecem em cada caixa de seleção)
   - pares:      [item, alvo certo]

   As opções e a ordem das questões são embaralhadas a cada rodada.
   ============================================================== */


/* Tópicos oficiais do exame CCNA 200-301 */
const TOPICOS = [
  "Fundamentos de rede",
  "Acesso à rede",
  "Conectividade IP",
  "Serviços IP",
  "Fundamentos de segurança",
  "Automação e programabilidade",
];


const QUESTOES = [
  /* ---------------------------------------------------------------
     ITN · Introduction to Networks
     --------------------------------------------------------------- */
  {
    id: "itn-01",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Um switch recebe um quadro unicast cujo endereço MAC de destino não está na tabela MAC. O que o switch faz com esse quadro?",
    opcoes: [
      "Descarta o quadro e envia uma mensagem ICMP à origem.",
      "Encaminha o quadro por todas as portas da VLAN, exceto a porta de origem.",
      "Envia uma requisição ARP para descobrir a porta de destino.",
      "Encaminha o quadro apenas pela porta do gateway padrão.",
    ],
    certas: [1],
    explicacao: "Sem o destino na tabela, o switch faz flooding (inundação): copia o quadro para todas as portas da VLAN, menos a de entrada. Quando o destino responder, o switch aprende a porta dele.",
  },
  {
    id: "itn-02",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Uma filial precisa de uma sub-rede para 50 hosts. Qual prefixo atende a necessidade com o menor desperdício de endereços?",
    opcoes: ["/25", "/26", "/27", "/28"],
    certas: [1],
    explicacao: "Um /26 tem 6 bits de host: 2⁶ − 2 = 62 hosts válidos. Um /27 teria só 30, que não bastam. Um /25 teria 126, com mais desperdício.",
  },
  {
    id: "itn-03",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "multipla",
    enunciado: "Quais duas características pertencem ao UDP? (Escolha duas.)",
    opcoes: [
      "Não estabelece conexão antes de enviar os dados.",
      "Confirma o recebimento de cada segmento.",
      "Tem um cabeçalho menor que o do TCP.",
      "Controla o fluxo com janelas deslizantes.",
      "Reordena os segmentos que chegam fora de ordem.",
    ],
    certas: [0, 2],
    explicacao: "O UDP não tem conexão nem confirmações, e o cabeçalho tem só 8 bytes. Confirmação, janelas e reordenação são recursos do TCP.",
  },
  {
    id: "itn-04",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Os computadores da rede 192.168.20.0/24 não conseguem alcançar o gateway R1. Observe a saída. Qual comando resolve o problema?",
    exibicao: `R1# show ip interface brief
Interface            IP-Address    OK? Method Status                Protocol
GigabitEthernet0/0/0 192.168.10.1  YES manual up                    up
GigabitEthernet0/0/1 192.168.20.1  YES manual administratively down down
Serial0/1/0          unassigned    YES unset  down                  down`,
    opcoes: [
      "no shutdown na interface GigabitEthernet0/0/1",
      "ip address 192.168.20.1 255.255.255.0 na interface GigabitEthernet0/0/1",
      "clock rate 64000 na interface Serial0/1/0",
      "copy running-config startup-config",
    ],
    certas: [0],
    explicacao: "O status \"administratively down\" indica que a interface foi desligada com shutdown. O endereço já está certo; falta ativar a interface com no shutdown.",
  },
  {
    id: "itn-05",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "associar",
    enunciado: "Associe cada PDU à camada do modelo OSI em que ela é criada.",
    alvos: ["Física", "Enlace", "Rede", "Transporte"],
    pares: [
      ["Segmento", "Transporte"],
      ["Pacote", "Rede"],
      ["Quadro", "Enlace"],
      ["Bits", "Física"],
    ],
    explicacao: "No encapsulamento, os dados viram segmento na camada de transporte, pacote na camada de rede, quadro na camada de enlace e bits na camada física.",
  },
  {
    id: "itn-06",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Qual é uma forma abreviada válida do endereço 2001:0db8:0000:0000:00a0:0000:0000:0001?",
    opcoes: [
      "2001:db8::a0::1",
      "2001:db8::a:0:0:1",
      "2001:db8::a0:0:0:1",
      "2001:db8:a0::1",
    ],
    certas: [2],
    explicacao: "Os zeros à esquerda de cada grupo podem sair (00a0 vira a0, nunca a). O :: substitui uma única sequência de grupos zerados, então não pode aparecer duas vezes. A última opção perdeu os dois grupos zerados antes de a0.",
  },
  {
    id: "itn-07",
    curso: "ITN",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "O PC1 (192.168.1.10/24) envia dados para um servidor em 10.0.0.5. Qual endereço MAC de destino o PC1 coloca no quadro?",
    opcoes: [
      "O MAC do servidor",
      "O MAC da interface do gateway padrão",
      "O MAC de broadcast FFFF.FFFF.FFFF",
      "O MAC do switch ao qual o PC1 está ligado",
    ],
    certas: [1],
    explicacao: "O destino está em outra rede, então o quadro vai até o gateway padrão. O IP de destino continua sendo o do servidor; só o MAC aponta para o roteador. A cada salto, o roteador cria um quadro novo.",
  },
  {
    id: "itn-08",
    curso: "ITN",
    topico: "Serviços IP",
    tipo: "multipla",
    enunciado: "Um técnico vai gerar as chaves RSA para habilitar o SSH em um switch novo. Quais duas configurações precisam existir antes do comando crypto key generate rsa? (Escolha duas.)",
    opcoes: [
      "Um nome de domínio, com ip domain-name",
      "Um hostname diferente do padrão",
      "A senha enable secret",
      "O comando transport input ssh nas linhas VTY",
      "O comando ip ssh version 2",
    ],
    certas: [0, 1],
    explicacao: "O nome da chave RSA é formado pelo hostname e pelo domínio, por isso os dois são exigidos. As outras configurações também fazem parte do SSH seguro, mas vêm depois ou não impedem a geração das chaves.",
  },
  {
    id: "itn-09",
    curso: "ITN",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "O PC1 acessa as impressoras da própria rede, mas não acessa a internet. Observe as saídas. Qual é a causa mais provável?",
    exibicao: `C:\\> ipconfig
   Endereço IPv4 . . . . . . : 192.168.1.10
   Máscara de Sub-rede . . . : 255.255.255.0
   Gateway Padrão. . . . . . : 192.168.1.254

R1# show ip interface brief | include GigabitEthernet0/0/0
GigabitEthernet0/0/0 192.168.1.1  YES manual up  up`,
    opcoes: [
      "A máscara de sub-rede do PC1 está errada.",
      "O gateway padrão do PC1 está configurado com o endereço errado.",
      "A interface G0/0/0 de R1 está desligada.",
      "O PC1 está sem endereço IPv4.",
    ],
    certas: [1],
    explicacao: "A interface de R1 na LAN é 192.168.1.1, mas o PC1 aponta para 192.168.1.254. A comunicação local funciona porque não usa o gateway; tudo o que sai da rede falha.",
  },
  {
    id: "itn-10",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Qual é o endereço de broadcast da sub-rede do host 172.16.45.130/27?",
    opcoes: ["172.16.45.127", "172.16.45.159", "172.16.45.191", "172.16.45.255"],
    certas: [1],
    explicacao: "Um /27 forma blocos de 32 endereços: 128 a 159 no último octeto. O host .130 está nesse bloco, então a rede é .128 e o broadcast é .159.",
  },
  {
    id: "itn-11",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Um técnico terminou de configurar um roteador. Qual comando garante que a configuração continue lá depois de uma reinicialização?",
    opcoes: [
      "copy startup-config running-config",
      "write erase",
      "copy running-config startup-config",
      "show running-config",
    ],
    certas: [2],
    explicacao: "A running-config fica na RAM e se perde ao reiniciar. Copiar para a startup-config grava na NVRAM, que é lida na inicialização.",
  },
  {
    id: "itn-12",
    curso: "ITN",
    topico: "Serviços IP",
    tipo: "associar",
    enunciado: "Associe cada protocolo à porta padrão que ele usa no servidor.",
    alvos: ["22", "53", "67", "443"],
    pares: [
      ["SSH", "22"],
      ["DNS", "53"],
      ["DHCP (servidor)", "67"],
      ["HTTPS", "443"],
    ],
    explicacao: "SSH usa a porta TCP 22, DNS a porta 53 (UDP e TCP), o servidor DHCP a porta UDP 67 e o HTTPS a porta TCP 443.",
  },
  {
    id: "itn-13",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Qual afirmação descreve a fibra óptica monomodo?",
    opcoes: [
      "Usa LED como fonte de luz e alcança distâncias curtas.",
      "Usa laser como fonte de luz e alcança distâncias longas.",
      "Tem núcleo maior que o da fibra multimodo.",
      "Sofre mais interferência eletromagnética que o cabo de cobre.",
    ],
    certas: [1],
    explicacao: "A monomodo tem núcleo fino e usa laser, por isso alcança dezenas de quilômetros. A multimodo tem núcleo maior, usa LED e serve para distâncias menores. Nenhuma fibra sofre interferência eletromagnética.",
  },
  {
    id: "itn-14",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "multipla",
    enunciado: "Um host IPv6 usa SLAAC para se configurar. Quais duas mensagens ICMPv6 ele usa para descobrir o prefixo da rede e o gateway? (Escolha duas.)",
    opcoes: [
      "Router Solicitation (RS)",
      "Router Advertisement (RA)",
      "Echo Request",
      "Neighbor Advertisement (NA)",
      "Destination Unreachable",
    ],
    certas: [0, 1],
    explicacao: "O host pede com uma RS, e o roteador responde com uma RA, que traz o prefixo e o próprio endereço link-local como gateway. NS e NA servem para resolver endereços, como o ARP no IPv4.",
  },
  {
    id: "itn-15",
    curso: "ITN",
    topico: "Fundamentos de segurança",
    tipo: "unica",
    enunciado: "Um atacante envia milhares de quadros com endereços MAC de origem falsos para um switch. Depois disso, o switch passa a encaminhar o tráfego por todas as portas. Que ataque é esse?",
    opcoes: [
      "Estouro da tabela MAC (MAC flooding)",
      "Falsificação de ARP (ARP spoofing)",
      "Esgotamento do DHCP (DHCP starvation)",
      "Salto de VLAN (VLAN hopping)",
    ],
    certas: [0],
    explicacao: "Os MACs falsos enchem a tabela MAC. Sem espaço para aprender, o switch inunda o tráfego e o atacante consegue capturá-lo. O port security limita os MACs por porta e evita o ataque.",
  },
  {
    id: "itn-16",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Um técnico vê o prompt Switch(config-if)# no console. Em que modo do IOS ele está?",
    opcoes: [
      "EXEC de usuário",
      "EXEC privilegiado",
      "Configuração global",
      "Configuração de interface",
    ],
    certas: [3],
    explicacao: "O (config-if) indica o modo de configuração de interface, aberto com o comando interface a partir da configuração global. Os comandos digitados ali valem só para aquela interface.",
  },
  {
    id: "itn-17",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "associar",
    enunciado: "Associe cada prompt ao modo do Cisco IOS que ele representa.",
    alvos: ["EXEC de usuário", "EXEC privilegiado", "Configuração global", "Configuração de linha"],
    pares: [
      ["Switch>", "EXEC de usuário"],
      ["Switch#", "EXEC privilegiado"],
      ["Switch(config)#", "Configuração global"],
      ["Switch(config-line)#", "Configuração de linha"],
    ],
    explicacao: "O > indica o EXEC de usuário (só consulta). O # indica o EXEC privilegiado, aberto com enable. Com configure terminal entra-se na configuração global, e com line console 0 ou line vty 0 15, na configuração de linha.",
  },
  {
    id: "itn-18",
    curso: "ITN",
    topico: "Fundamentos de segurança",
    tipo: "unica",
    enunciado: "Qual comando faz com que as senhas em texto claro deixem de aparecer legíveis no show running-config?",
    opcoes: [
      "service password-encryption",
      "enable secret",
      "security passwords min-length 10",
      "login local",
    ],
    certas: [0],
    explicacao: "O service password-encryption cifra as senhas de console, VTY e enable password na configuração (tipo 7). É uma proteção fraca, só contra quem olha a tela. O enable secret protege apenas a senha do modo privilegiado.",
  },
  {
    id: "itn-19",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "multipla",
    enunciado: "Quais dois endereços IPv4 são privados, conforme a RFC 1918? (Escolha dois.)",
    opcoes: ["172.20.4.1", "192.168.200.10", "172.32.0.1", "192.169.1.1", "100.64.0.1"],
    certas: [0, 1],
    explicacao: "As faixas privadas são 10.0.0.0/8, 172.16.0.0/12 (172.16 a 172.31) e 192.168.0.0/16. 172.32 e 192.169 ficam fora delas. 100.64.0.0/10 é o espaço compartilhado do CGNAT, não é RFC 1918.",
  },
  {
    id: "itn-20",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Um PC com Windows, configurado para obter endereço automaticamente, mostra o IPv4 169.254.18.7. O que isso indica?",
    opcoes: [
      "O PC não recebeu resposta de um servidor DHCP.",
      "O endereço foi configurado manualmente pelo usuário.",
      "O PC recebeu um endereço público do provedor.",
      "O PC está usando o endereço de loopback.",
    ],
    certas: [0],
    explicacao: "Sem resposta do DHCP, o sistema se atribui um endereço APIPA da faixa 169.254.0.0/16. Com ele, o PC só fala com vizinhos na mesma situação e não sai da rede local.",
  },
  {
    id: "itn-21",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Qual é o endereço decimal correspondente a 11000000.10101000.00001010.00000001?",
    opcoes: ["192.168.10.1", "192.164.10.1", "196.168.10.1", "192.168.5.1"],
    certas: [0],
    explicacao: "11000000 = 128 + 64 = 192. 10101000 = 128 + 32 + 8 = 168. 00001010 = 8 + 2 = 10. 00000001 = 1.",
  },
  {
    id: "itn-22",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Qual é o valor hexadecimal do número decimal 172?",
    opcoes: ["AC", "CA", "B2", "AB"],
    certas: [0],
    explicacao: "172 ÷ 16 = 10, com resto 12. O 10 vira A e o 12 vira C: AC. Conferindo: 10 × 16 + 12 = 172.",
  },
  {
    id: "itn-23",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Qual método de comutação recebe o quadro inteiro e confere o FCS antes de encaminhá-lo?",
    opcoes: ["Store-and-forward", "Cut-through", "Fragment-free", "Fast-forward"],
    certas: [0],
    explicacao: "No store-and-forward, o switch guarda o quadro todo e descarta os que têm erro no FCS. O cut-through começa a encaminhar logo após ler o MAC de destino. Fast-forward e fragment-free são variações do cut-through.",
  },
  {
    id: "itn-24",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Para que serve o campo FCS no final de um quadro Ethernet?",
    opcoes: [
      "Detectar se o quadro foi corrompido na transmissão",
      "Identificar o protocolo da camada superior",
      "Colocar os quadros em ordem no destino",
      "Indicar o endereço MAC de destino",
    ],
    certas: [0],
    explicacao: "O FCS (Frame Check Sequence) leva um CRC calculado pela origem. O destino refaz o cálculo; se o valor não bater, o quadro é descartado. O protocolo superior é indicado pelo campo EtherType.",
  },
  {
    id: "itn-25",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "multipla",
    enunciado: "Quais duas afirmações sobre a comunicação full-duplex são verdadeiras? (Escolha duas.)",
    opcoes: [
      "Os dois lados enviam e recebem ao mesmo tempo.",
      "Não há colisões, então o CSMA/CD não é necessário.",
      "É o modo usado nas portas de um hub.",
      "Exige cabo coaxial.",
      "Dobra o tamanho máximo do quadro Ethernet.",
    ],
    certas: [0, 1],
    explicacao: "No full-duplex, cada sentido tem seu próprio caminho, por isso não há colisão e o CSMA/CD fica desligado. Hubs só trabalham em half-duplex.",
  },
  {
    id: "itn-26",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Qual campo do cabeçalho IPv4 impede que um pacote circule para sempre em um loop de roteamento?",
    opcoes: ["TTL (Time to Live)", "Checksum do cabeçalho", "Identificação", "DS (Differentiated Services)"],
    certas: [0],
    explicacao: "Cada roteador diminui o TTL em 1. Quando chega a zero, o pacote é descartado e o roteador avisa a origem com um ICMP Time Exceeded. No IPv6, o campo equivalente se chama Hop Limit.",
  },
  {
    id: "itn-27",
    curso: "ITN",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "R1 recebe um pacote destinado a 10.1.2.50. Observe a tabela. Para qual próximo salto R1 encaminha o pacote?",
    exibicao: `R1# show ip route
Gateway of last resort is 209.165.200.226 to network 0.0.0.0

S*    0.0.0.0/0 [1/0] via 209.165.200.226
      10.0.0.0/8 is variably subnetted, 4 subnets, 3 masks
C        10.1.1.0/24 is directly connected, GigabitEthernet0/0/0
L        10.1.1.1/32 is directly connected, GigabitEthernet0/0/0
S        10.1.0.0/16 [1/0] via 10.1.1.2
S        10.1.2.0/24 [1/0] via 10.1.1.3`,
    opcoes: ["10.1.1.3", "10.1.1.2", "209.165.200.226", "Nenhum: o pacote é descartado."],
    certas: [0],
    explicacao: "O destino combina com 10.1.0.0/16 e com 10.1.2.0/24. O roteador escolhe o prefixo mais longo (a correspondência mais específica), /24, via 10.1.1.3.",
  },
  {
    id: "itn-28",
    curso: "ITN",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "R1 recebe um pacote destinado a 10.2.0.1. Observe a tabela. Para qual próximo salto R1 encaminha o pacote?",
    exibicao: `R1# show ip route
Gateway of last resort is 209.165.200.226 to network 0.0.0.0

S*    0.0.0.0/0 [1/0] via 209.165.200.226
      10.0.0.0/8 is variably subnetted, 4 subnets, 3 masks
C        10.1.1.0/24 is directly connected, GigabitEthernet0/0/0
L        10.1.1.1/32 is directly connected, GigabitEthernet0/0/0
S        10.1.0.0/16 [1/0] via 10.1.1.2
S        10.1.2.0/24 [1/0] via 10.1.1.3`,
    opcoes: ["209.165.200.226", "10.1.1.2", "10.1.1.3", "Nenhum: o pacote é descartado."],
    certas: [0],
    explicacao: "10.2.0.1 não está em 10.1.0.0/16 nem em nenhuma rota mais específica. Só a rota padrão 0.0.0.0/0 combina, então o pacote vai para o gateway of last resort, 209.165.200.226.",
  },
  {
    id: "itn-29",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "No IPv6, o que um host usa para descobrir o endereço MAC de um vizinho, no lugar do ARP?",
    opcoes: [
      "Mensagens Neighbor Solicitation e Neighbor Advertisement do ICMPv6",
      "Uma consulta ao servidor DHCPv6",
      "Um broadcast IPv6 para FF:FF:FF:FF:FF:FF",
      "O protocolo ARPv6",
    ],
    certas: [0],
    explicacao: "O Neighbor Discovery do ICMPv6 envia uma NS para um endereço multicast; o dono do IP responde com uma NA contendo o MAC. O IPv6 não tem broadcast, e ARPv6 não existe.",
  },
  {
    id: "itn-30",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Qual prefixo identifica um endereço IPv6 link-local?",
    opcoes: ["FE80::/10", "FF00::/8", "2000::/3", "FC00::/7"],
    certas: [0],
    explicacao: "Link-local começa com FE80::/10 e só vale no enlace local. FF00::/8 é multicast, 2000::/3 é unicast global e FC00::/7 é unique local.",
  },
  {
    id: "itn-31",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "associar",
    enunciado: "Associe cada endereço IPv6 ao seu tipo.",
    alvos: ["Unicast global", "Link-local", "Multicast", "Loopback"],
    pares: [
      ["2001:db8:acad:1::10", "Unicast global"],
      ["fe80::1", "Link-local"],
      ["ff02::1", "Multicast"],
      ["::1", "Loopback"],
    ],
    explicacao: "Endereços que começam de 2000 a 3FFF são unicast global; FE80 é link-local; FF é multicast (ff02::1 = todos os nós do enlace); ::1 é o loopback, como o 127.0.0.1 do IPv4.",
  },
  {
    id: "itn-32",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Uma interface com MAC 00:1A:2B:3C:4D:5E gera o ID de interface pelo processo EUI-64. Qual é o resultado?",
    opcoes: [
      "021A:2BFF:FE3C:4D5E",
      "001A:2BFF:FE3C:4D5E",
      "021A:2BFE:FF3C:4D5E",
      "001A:2B3C:4D5E:FFFE",
    ],
    certas: [0],
    explicacao: "O EUI-64 divide o MAC ao meio, insere FFFE no centro (001A:2BFF:FE3C:4D5E) e inverte o 7º bit do primeiro byte: 00 vira 02. Resultado: 021A:2BFF:FE3C:4D5E.",
  },
  {
    id: "itn-33",
    curso: "ITN",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "Como o traceroute descobre cada roteador no caminho até o destino?",
    opcoes: [
      "Envia pacotes com TTL crescente e recebe um ICMP Time Exceeded de cada salto.",
      "Lê a tabela de roteamento de cada roteador do caminho.",
      "Envia requisições ARP para cada roteador do caminho.",
      "Consulta o servidor DNS, que guarda a lista de roteadores.",
    ],
    certas: [0],
    explicacao: "O primeiro pacote sai com TTL 1 e morre no primeiro roteador, que responde com Time Exceeded. Depois TTL 2, 3 e assim por diante, até o destino responder.",
  },
  {
    id: "itn-34",
    curso: "ITN",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "Um técnico testa a conectividade logo após configurar a rede. Observe a saída. O que o primeiro ponto indica com mais probabilidade?",
    exibicao: `R1# ping 192.168.30.10
Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 192.168.30.10, timeout is 2 seconds:
.!!!!
Success rate is 80 percent (4/5), round-trip min/avg/max = 1/2/4 ms`,
    opcoes: [
      "O primeiro pacote expirou enquanto o ARP descobria o endereço MAC.",
      "O destino está inalcançável.",
      "Uma ACL está bloqueando parte do tráfego ICMP.",
      "O link está congestionado de forma permanente.",
    ],
    certas: [0],
    explicacao: "Na primeira tentativa, o roteador ainda precisa resolver o MAC com ARP, e o primeiro eco pode expirar. Os outros quatro chegam (!). Destino inalcançável apareceria como U.",
  },
  {
    id: "itn-35",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Qual faixa corresponde às portas bem conhecidas (well-known), usadas por serviços como HTTP e SSH?",
    opcoes: ["0 a 1023", "1024 a 49151", "49152 a 65535", "0 a 65535"],
    certas: [0],
    explicacao: "As portas de 0 a 1023 são bem conhecidas. De 1024 a 49151 são as registradas, e de 49152 a 65535 são as dinâmicas, usadas como porta de origem pelos clientes.",
  },
  {
    id: "itn-36",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Qual é a sequência correta do handshake de três vias que abre uma conexão TCP?",
    opcoes: ["SYN, SYN-ACK, ACK", "SYN, ACK, SYN-ACK", "ACK, SYN, FIN", "SYN, SYN, ACK"],
    certas: [0],
    explicacao: "O cliente envia SYN, o servidor responde SYN-ACK e o cliente confirma com ACK. Para encerrar, o TCP usa FIN e ACK.",
  },
  {
    id: "itn-37",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "multipla",
    enunciado: "Quais dois recursos o TCP usa para garantir a entrega confiável dos dados? (Escolha dois.)",
    opcoes: [
      "Números de sequência",
      "Confirmações (ACK)",
      "Endereços de broadcast",
      "O campo TTL",
      "Comunicação sem conexão",
    ],
    certas: [0, 1],
    explicacao: "Os números de sequência permitem remontar os dados na ordem certa e perceber o que falta. Os ACKs confirmam o que chegou, e o que não for confirmado é retransmitido.",
  },
  {
    id: "itn-38",
    curso: "ITN",
    topico: "Serviços IP",
    tipo: "associar",
    enunciado: "Coloque as mensagens do DHCPv4 na ordem em que acontecem quando um cliente obtém um endereço.",
    alvos: ["1ª", "2ª", "3ª", "4ª"],
    pares: [
      ["DHCPDISCOVER", "1ª"],
      ["DHCPOFFER", "2ª"],
      ["DHCPREQUEST", "3ª"],
      ["DHCPACK", "4ª"],
    ],
    explicacao: "É o processo DORA: o cliente procura (Discover), o servidor oferece (Offer), o cliente pede o endereço oferecido (Request) e o servidor confirma (Acknowledgment).",
  },
  {
    id: "itn-39",
    curso: "ITN",
    topico: "Serviços IP",
    tipo: "unica",
    enunciado: "Uma usuária lê os e-mails no notebook e no celular e quer que as mensagens continuem no servidor, sincronizadas. Qual protocolo atende?",
    opcoes: ["IMAP", "POP3", "SMTP", "SNMP"],
    certas: [0],
    explicacao: "O IMAP mantém as mensagens no servidor e sincroniza pastas entre dispositivos. O POP3 costuma baixar e apagar do servidor. O SMTP envia e-mails, e o SNMP gerencia dispositivos de rede.",
  },
  {
    id: "itn-40",
    curso: "ITN",
    topico: "Serviços IP",
    tipo: "unica",
    enunciado: "Qual tipo de registro DNS associa um nome de domínio a um endereço IPv6?",
    opcoes: ["AAAA", "A", "MX", "NS"],
    certas: [0],
    explicacao: "O registro A associa nome a IPv4, e o AAAA (quad-A) associa nome a IPv6. MX indica o servidor de e-mail do domínio, e NS indica o servidor de nomes autoritativo.",
  },
  {
    id: "itn-41",
    curso: "ITN",
    topico: "Fundamentos de segurança",
    tipo: "unica",
    enunciado: "Milhares de computadores infectados enviam tráfego ao mesmo tempo para o site de uma empresa, que sai do ar. Que tipo de ataque é esse?",
    opcoes: [
      "Negação de serviço distribuída (DDoS)",
      "Ataque de reconhecimento",
      "Ataque de acesso por força bruta",
      "Engenharia social",
    ],
    certas: [0],
    explicacao: "Um DoS busca deixar o serviço indisponível. Quando o tráfego parte de muitas origens, geralmente uma botnet, é um DDoS. Reconhecimento é coletar informações, e força bruta tenta adivinhar senhas.",
  },
  {
    id: "itn-42",
    curso: "ITN",
    topico: "Fundamentos de segurança",
    tipo: "multipla",
    enunciado: "Quais duas medidas reforçam a segurança do acesso remoto a um roteador? (Escolha duas.)",
    opcoes: [
      "Usar SSH em vez de Telnet",
      "Configurar login block-for para bloquear tentativas repetidas",
      "Deixar as linhas VTY sem senha para facilitar a gerência",
      "Usar enable password em vez de enable secret",
      "Habilitar o servidor HTTP do roteador",
    ],
    certas: [0, 1],
    explicacao: "O SSH cifra a sessão, enquanto o Telnet envia tudo em texto claro. O login block-for dificulta ataques de força bruta. O enable secret é mais forte que o enable password.",
  },
  {
    id: "itn-43",
    curso: "ITN",
    topico: "Acesso à rede",
    tipo: "unica",
    enunciado: "Qual comando mostra o modelo, a interface e o endereço dos dispositivos Cisco diretamente conectados a um switch?",
    opcoes: ["show cdp neighbors detail", "show ip route", "show arp", "show mac address-table"],
    certas: [0],
    explicacao: "O CDP (Cisco Discovery Protocol) troca informações entre vizinhos Cisco diretamente conectados. Com detail, a saída inclui o endereço IP e a versão do IOS. O padrão aberto equivalente é o LLDP.",
  },
  {
    id: "itn-44",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Os usuários ligados à porta Fa0/1 de S1 reclamam de lentidão. A porta do outro lado do link está em full-duplex. Observe a saída. Qual é a causa provável?",
    exibicao: `S1# show interfaces FastEthernet0/1
FastEthernet0/1 is up, line protocol is up (connected)
  Hardware is Fast Ethernet, address is 0019.e86a.6f81
  Half-duplex, 100Mb/s, media type is 10/100BaseTX
  ...
     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored
     2210 output errors, 2210 collisions, 0 interface resets
     2210 late collision, 0 deferred`,
    opcoes: [
      "Incompatibilidade de duplex entre as duas pontas do link",
      "Cabo com pinagem errada",
      "Porta configurada na VLAN errada",
      "Endereço IP duplicado na rede",
    ],
    certas: [0],
    explicacao: "S1 está em half-duplex e o vizinho em full-duplex. O lado half-duplex registra colisões tardias (late collision), sintoma típico de incompatibilidade de duplex. A solução é configurar os dois lados iguais.",
  },
  {
    id: "itn-45",
    curso: "ITN",
    topico: "Acesso à rede",
    tipo: "unica",
    enunciado: "Qual padrão IEEE define as redes locais sem fio (Wi-Fi)?",
    opcoes: ["802.11", "802.3", "802.15", "802.1Q"],
    certas: [0],
    explicacao: "O 802.11 define as WLANs (Wi-Fi). O 802.3 é a Ethernet cabeada, o 802.15 cobre redes pessoais como o Bluetooth e o 802.1Q define a marcação de VLANs nos trunks.",
  },
  {
    id: "itn-46",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Um técnico divide 192.168.1.0/24 com VLSM. A maior sub-rede já ficou com 192.168.1.0/25. Qual é a próxima sub-rede para um setor de 50 hosts, com o menor desperdício?",
    opcoes: ["192.168.1.128/26", "192.168.1.64/26", "192.168.1.100/26", "192.168.1.128/25"],
    certas: [0],
    explicacao: "O /25 usou de .0 a .127, então a próxima começa em .128. Para 50 hosts, basta um /26 (62 hosts). .64 se sobrepõe ao /25, e .100 não é início de bloco de 64.",
  },
  {
    id: "itn-47",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Quantos endereços de host válidos existem em uma sub-rede com máscara 255.255.255.240?",
    opcoes: ["14", "16", "30", "6"],
    certas: [0],
    explicacao: "240 = 11110000, sobram 4 bits de host: 2⁴ = 16 endereços. Tirando rede e broadcast, ficam 14 hosts válidos. É um /28.",
  },
  {
    id: "itn-48",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Qual é o endereço de rede do host 10.45.200.17/20?",
    opcoes: ["10.45.192.0", "10.45.200.0", "10.45.208.0", "10.45.128.0"],
    certas: [0],
    explicacao: "Um /20 forma blocos de 16 no terceiro octeto: 192, 208, 224... O 200 fica no bloco de 192 a 207, então a rede é 10.45.192.0 e o broadcast é 10.45.207.255.",
  },
  {
    id: "itn-49",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Qual cabo liga a porta de console de um switch novo ao computador do técnico, para a configuração inicial?",
    opcoes: [
      "Cabo de console (rollover ou USB)",
      "Cabo cruzado (crossover)",
      "Cabo direto (straight-through)",
      "Fibra multimodo",
    ],
    certas: [0],
    explicacao: "A configuração inicial é feita pela porta de console, com cabo de console (rollover com RJ-45 e adaptador serial, ou USB) e um programa de terminal, como o PuTTY ou o terminal do Packet Tracer.",
  },
  {
    id: "itn-50",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Uma empresa dá aos fornecedores acesso seguro a uma parte da sua rede interna, para consultar pedidos. Como se chama esse tipo de rede?",
    opcoes: ["Extranet", "Intranet", "Internet", "Rede ponto a ponto"],
    certas: [0],
    explicacao: "Intranet é a rede interna, acessada só pela organização. Extranet é a parte da rede liberada com segurança para parceiros externos, como fornecedores e clientes.",
  },
  {
    id: "itn-51",
    curso: "ITN",
    topico: "Fundamentos de rede",
    tipo: "multipla",
    enunciado: "Quais duas características do cabo UTP ajudam a reduzir o crosstalk? (Escolha duas.)",
    opcoes: [
      "Os fios de cada par são trançados entre si.",
      "Cada par tem um número diferente de tranças por metro.",
      "Uma blindagem metálica envolve todos os pares.",
      "Os sinais são transmitidos como luz.",
      "O cabo usa conectores RJ-11.",
    ],
    certas: [0, 1],
    explicacao: "No UTP, o trançado faz os campos magnéticos dos fios se cancelarem, e as tranças diferentes em cada par reduzem a interferência entre pares. O UTP não tem blindagem (isso é o STP), usa RJ-45 e transmite sinais elétricos.",
  },

  /* ---------------------------------------------------------------
     SRWE · Switching, Routing and Wireless Essentials
     --------------------------------------------------------------- */
  {
    id: "srwe-01",
    curso: "SRWE",
    topico: "Acesso à rede",
    tipo: "unica",
    enunciado: "Qual é a VLAN nativa padrão em um trunk 802.1Q de um switch Cisco?",
    opcoes: ["VLAN 1", "VLAN 99", "VLAN 1002", "Não existe VLAN nativa por padrão."],
    certas: [0],
    explicacao: "Por padrão, a VLAN nativa é a VLAN 1, e os quadros dela atravessam o trunk sem marcação (tag). A boa prática é trocar a nativa por uma VLAN sem uso, igual nos dois lados do trunk.",
  },
  {
    id: "srwe-02",
    curso: "SRWE",
    topico: "Acesso à rede",
    tipo: "unica",
    enunciado: "Os PCs da VLAN 20 em S1 não alcançam os PCs da VLAN 20 em S2. As VLANs 10 e 30 funcionam. Observe a saída. Qual é a causa?",
    exibicao: `S1# show interfaces trunk
Port      Mode   Encapsulation  Status     Native vlan
Gi0/1     on     802.1q         trunking   1

Port      Vlans allowed on trunk
Gi0/1     10,30`,
    opcoes: [
      "A VLAN 20 não está permitida no trunk.",
      "A VLAN nativa está errada.",
      "A porta Gi0/1 está em modo de acesso.",
      "O trunk está usando encapsulamento ISL.",
    ],
    certas: [0],
    explicacao: "O trunk só deixa passar as VLANs 10 e 30. O comando switchport trunk allowed vlan add 20 inclui a VLAN 20 sem apagar as outras. Cuidado: sem o add, a lista é substituída.",
  },
  {
    id: "srwe-03",
    curso: "SRWE",
    topico: "Acesso à rede",
    tipo: "unica",
    enunciado: "Quais comandos colocam uma porta do switch somente na VLAN 30, para ligar um PC?",
    opcoes: [
      "switchport mode access e switchport access vlan 30",
      "switchport mode trunk e switchport trunk native vlan 30",
      "vlan 30 e name 30",
      "switchport trunk allowed vlan 30",
    ],
    certas: [0],
    explicacao: "Uma porta de acesso pertence a uma única VLAN. O mode access fixa o modo (e evita a negociação de trunk), e o access vlan 30 define a VLAN. Os comandos vlan 30 e name só criam e nomeiam a VLAN.",
  },
  {
    id: "srwe-04",
    curso: "SRWE",
    topico: "Acesso à rede",
    tipo: "multipla",
    enunciado: "Quais duas afirmações sobre VLANs são verdadeiras? (Escolha duas.)",
    opcoes: [
      "Cada VLAN é um domínio de broadcast separado.",
      "A comunicação entre VLANs exige roteamento.",
      "As VLANs aumentam o domínio de colisão.",
      "Hosts de VLANs diferentes se comunicam sem roteador se estiverem no mesmo switch.",
      "VLANs só funcionam em switches de camada 3.",
    ],
    certas: [0, 1],
    explicacao: "Um broadcast fica preso à sua VLAN. Para ir de uma VLAN a outra, é preciso um roteador (router-on-a-stick) ou um switch de camada 3 com SVIs, mesmo que os hosts estejam no mesmo switch.",
  },
  {
    id: "srwe-05",
    curso: "SRWE",
    topico: "Acesso à rede",
    tipo: "unica",
    enunciado: "Observe a configuração de um router-on-a-stick. O que o comando encapsulation dot1Q 20 faz?",
    exibicao: `R1(config)# interface GigabitEthernet0/0/1.20
R1(config-subif)# encapsulation dot1Q 20
R1(config-subif)# ip address 192.168.20.1 255.255.255.0`,
    opcoes: [
      "Associa a subinterface ao tráfego marcado com a VLAN 20.",
      "Cria a VLAN 20 no switch vizinho.",
      "Define a VLAN 20 como VLAN nativa do trunk.",
      "Ativa o modo trunk na porta do switch.",
    ],
    certas: [0],
    explicacao: "Cada subinterface atende uma VLAN: o dot1Q 20 faz ela receber e enviar quadros com a tag 20, e o IP vira o gateway da VLAN. A porta do switch ligada ao roteador precisa estar em trunk.",
  },
  {
    id: "srwe-06",
    curso: "SRWE",
    topico: "Acesso à rede",
    tipo: "unica",
    enunciado: "Em um switch multicamada, o que permite rotear entre VLANs sem um roteador externo?",
    opcoes: [
      "SVIs (interface vlan) com endereço IP e o comando ip routing",
      "Subinterfaces com encapsulation dot1Q",
      "O protocolo DTP",
      "O protocolo VTP",
    ],
    certas: [0],
    explicacao: "Cada VLAN ganha uma SVI com IP, que serve de gateway. O ip routing liga o roteamento no switch. É mais rápido e escala melhor que o router-on-a-stick.",
  },
  {
    id: "srwe-07",
    curso: "SRWE",
    topico: "Acesso à rede",
    tipo: "unica",
    enunciado: "Como o STP escolhe a ponte raiz (root bridge)?",
    opcoes: [
      "Pelo menor bridge ID: primeiro a menor prioridade e, em empate, o menor MAC.",
      "Pela maior prioridade configurada.",
      "Pelo maior endereço MAC.",
      "Pelo switch com mais portas ativas.",
    ],
    certas: [0],
    explicacao: "O bridge ID junta prioridade (padrão 32768 + número da VLAN) e MAC. Vence o menor. Para controlar a eleição, diminua a prioridade do switch desejado, por exemplo com spanning-tree vlan 1 root primary.",
  },
  {
    id: "srwe-08",
    curso: "SRWE",
    topico: "Acesso à rede",
    tipo: "unica",
    enunciado: "Três switches rodam STP na VLAN 1. Observe os bridge IDs. Qual switch será a ponte raiz?",
    exibicao: `Switch  Prioridade  MAC
S1      32769       000A.0001.1111
S2      24577       000C.0002.2222
S3      32769       0009.0003.3333`,
    opcoes: ["S2", "S1", "S3", "Há empate, e nenhum é eleito."],
    certas: [0],
    explicacao: "A prioridade é comparada primeiro, e S2 tem a menor (24577). O MAC só desempata quando as prioridades são iguais; por isso o MAC menor de S3 não importa aqui.",
  },
  {
    id: "srwe-09",
    curso: "SRWE",
    topico: "Acesso à rede",
    tipo: "unica",
    enunciado: "Qual recurso faz uma porta de acesso ir direto para o estado de encaminhamento, sem passar por listening e learning?",
    opcoes: ["PortFast", "BPDU Guard", "Root Guard", "EtherChannel"],
    certas: [0],
    explicacao: "O PortFast é para portas ligadas a hosts: o PC ganha rede na hora, sem esperar a convergência do STP. Nunca use em portas que levam a outros switches.",
  },
  {
    id: "srwe-10",
    curso: "SRWE",
    topico: "Acesso à rede",
    tipo: "unica",
    enunciado: "Uma porta com PortFast e BPDU Guard recebe um BPDU porque alguém ligou um switch nela. O que acontece?",
    opcoes: [
      "A porta entra em estado err-disabled.",
      "A porta vira porta raiz.",
      "O BPDU é ignorado e a porta continua normal.",
      "A porta muda automaticamente para trunk.",
    ],
    certas: [0],
    explicacao: "O BPDU Guard desativa a porta ao receber um BPDU, para evitar loops e switches não autorizados. Para reativar: tire o switch e use shutdown e no shutdown, ou configure a recuperação automática.",
  },
  {
    id: "srwe-11",
    curso: "SRWE",
    topico: "Acesso à rede",
    tipo: "associar",
    enunciado: "Associe cada descrição à função de porta do STP/RSTP.",
    alvos: ["Porta raiz", "Porta designada", "Porta alternativa", "Porta desabilitada"],
    pares: [
      ["Em um switch não raiz, a porta com o melhor caminho até a ponte raiz", "Porta raiz"],
      ["A porta que encaminha os quadros em cada segmento", "Porta designada"],
      ["A porta bloqueada para evitar loop, pronta para assumir", "Porta alternativa"],
      ["A porta desligada administrativamente", "Porta desabilitada"],
    ],
    explicacao: "Todo switch não raiz tem uma porta raiz. Cada segmento tem uma porta designada. As que sobram ficam bloqueadas (alternativas, no RSTP) e assumem se o caminho principal cair.",
  },
  {
    id: "srwe-12",
    curso: "SRWE",
    topico: "Acesso à rede",
    tipo: "unica",
    enunciado: "Qual combinação de modos nas duas pontas forma um EtherChannel com LACP?",
    opcoes: ["active e passive", "passive e passive", "desirable e auto", "on e active"],
    certas: [0],
    explicacao: "No LACP, pelo menos um lado precisa ser active. Passive com passive não negocia. Desirable e auto são modos do PAgP. O modo on não negocia e não conversa com active.",
  },
  {
    id: "srwe-13",
    curso: "SRWE",
    topico: "Acesso à rede",
    tipo: "multipla",
    enunciado: "Quais duas configurações precisam ser iguais em todas as interfaces de um EtherChannel? (Escolha duas.)",
    opcoes: [
      "Velocidade e duplex",
      "Modo da porta (acesso ou trunk) e VLANs",
      "A descrição (description) das interfaces",
      "O endereço MAC das interfaces",
      "O número das interfaces",
    ],
    certas: [0, 1],
    explicacao: "As portas do grupo precisam ter a mesma velocidade, o mesmo duplex e a mesma configuração de VLAN (mesma VLAN de acesso, ou mesmo trunk com as mesmas VLANs). Se algo divergir, o canal não se forma.",
  },
  {
    id: "srwe-14",
    curso: "SRWE",
    topico: "Serviços IP",
    tipo: "unica",
    enunciado: "Os PCs da VLAN 10 não recebem endereço. O servidor DHCP fica em outra rede, 10.0.0.5. O que configurar na interface do roteador que é gateway da VLAN 10?",
    opcoes: [
      "ip helper-address 10.0.0.5",
      "ip dhcp excluded-address 10.0.0.5",
      "ip address dhcp",
      "service dhcp",
    ],
    certas: [0],
    explicacao: "O Discover do DHCP é broadcast e não atravessa o roteador. O ip helper-address transforma esse broadcast em unicast para o servidor: é o relay DHCP.",
  },
  {
    id: "srwe-15",
    curso: "SRWE",
    topico: "Serviços IP",
    tipo: "unica",
    enunciado: "Um roteador é servidor DHCP da rede 192.168.10.0/24. Qual comando impede que ele entregue os endereços .1 a .10, reservados para o gateway e os servidores?",
    opcoes: [
      "ip dhcp excluded-address 192.168.10.1 192.168.10.10",
      "network 192.168.10.0 255.255.255.0",
      "default-router 192.168.10.1",
      "ip dhcp pool 192.168.10.1 192.168.10.10",
    ],
    certas: [0],
    explicacao: "O excluded-address é configurado no modo global, fora do pool. O network define a faixa do pool, e o default-router informa o gateway aos clientes.",
  },
  {
    id: "srwe-16",
    curso: "SRWE",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Um roteador envia mensagens RA com o flag M = 0 e o flag O = 1. Como os hosts IPv6 da rede se configuram?",
    opcoes: [
      "Criam o endereço por SLAAC e buscam DNS e outras informações em um servidor DHCPv6 sem estado.",
      "Recebem o endereço completo de um servidor DHCPv6 com estado.",
      "Usam só o SLAAC e ficam sem servidor DNS.",
      "Precisam de configuração manual.",
    ],
    certas: [0],
    explicacao: "M = 1 manda usar DHCPv6 com estado (o servidor entrega o endereço). Com M = 0 e O = 1, o host cria o próprio endereço (SLAAC) e pede ao DHCPv6 só as outras informações, como o DNS.",
  },
  {
    id: "srwe-17",
    curso: "SRWE",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "Qual é o objetivo de um protocolo de redundância de primeiro salto (FHRP), como o HSRP?",
    opcoes: [
      "Oferecer um gateway padrão redundante, com um IP virtual compartilhado por dois roteadores",
      "Balancear as rotas aprendidas pelo OSPF",
      "Evitar loops na camada 2",
      "Distribuir endereços IP aos hosts",
    ],
    certas: [0],
    explicacao: "Os hosts usam o IP virtual como gateway. Se o roteador ativo falhar, o de reserva assume esse IP e os hosts nem percebem. Evitar loops na camada 2 é papel do STP.",
  },
  {
    id: "srwe-18",
    curso: "SRWE",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "No HSRP, qual roteador é eleito como ativo?",
    opcoes: [
      "O de maior prioridade; em empate, o de maior endereço IP",
      "O de menor prioridade",
      "O de menor endereço IP",
      "Sempre o primeiro que foi ligado",
    ],
    certas: [0],
    explicacao: "A prioridade padrão é 100 e vence a maior. Em empate, vence o maior IP. Para um roteador de maior prioridade retomar o papel depois de voltar, é preciso configurar standby preempt.",
  },
  {
    id: "srwe-19",
    curso: "SRWE",
    topico: "Fundamentos de segurança",
    tipo: "unica",
    enunciado: "Qual modo de violação do port security descarta o tráfego de MACs desconhecidos, registra a violação e mantém a porta ativa?",
    opcoes: ["restrict", "protect", "shutdown", "err-disable"],
    certas: [0],
    explicacao: "O protect descarta sem registrar nada. O restrict descarta, gera log e soma no contador de violações. O shutdown, que é o padrão, coloca a porta em err-disabled.",
  },
  {
    id: "srwe-20",
    curso: "SRWE",
    topico: "Fundamentos de segurança",
    tipo: "unica",
    enunciado: "A porta Fa0/5 parou depois que alguém ligou nela um notebook desconhecido. O notebook já foi retirado. Observe a saída. Como reativar a porta?",
    exibicao: `S1# show port-security interface fa0/5
Port Security              : Enabled
Port Status                : Secure-shutdown
Violation Mode             : Shutdown
Maximum MAC Addresses      : 1
Total MAC Addresses        : 1
Sticky MAC Addresses       : 1
Last Source Address:Vlan   : 00e0.f7b0.086e:10
Security Violation Count   : 1`,
    opcoes: [
      "Executar shutdown e depois no shutdown na interface",
      "Reiniciar o PC autorizado",
      "Configurar a porta como trunk",
      "Aumentar a prioridade do STP na porta",
    ],
    certas: [0],
    explicacao: "No modo shutdown, a violação coloca a porta em err-disabled (Secure-shutdown). Depois de remover a causa, o shutdown seguido de no shutdown reativa a porta.",
  },
  {
    id: "srwe-21",
    curso: "SRWE",
    topico: "Fundamentos de segurança",
    tipo: "unica",
    enunciado: "Qual recurso do switch impede que um servidor DHCP falso, ligado a uma porta de usuário, responda aos clientes?",
    opcoes: ["DHCP snooping", "Dynamic ARP Inspection", "Port security", "BPDU Guard"],
    certas: [0],
    explicacao: "Com o DHCP snooping, só as portas confiáveis (trust), como o uplink para o servidor verdadeiro, podem enviar respostas DHCP. Nas demais, as ofertas são descartadas.",
  },
  {
    id: "srwe-22",
    curso: "SRWE",
    topico: "Fundamentos de segurança",
    tipo: "unica",
    enunciado: "Qual recurso usa a tabela de vínculos do DHCP snooping para descartar respostas ARP falsificadas?",
    opcoes: ["Dynamic ARP Inspection (DAI)", "PortFast", "Storm control", "VTP pruning"],
    certas: [0],
    explicacao: "A DAI confere se o par IP–MAC de cada ARP bate com a tabela do DHCP snooping. Respostas falsas, usadas em ataques man-in-the-middle, são descartadas.",
  },
  {
    id: "srwe-23",
    curso: "SRWE",
    topico: "Fundamentos de segurança",
    tipo: "multipla",
    enunciado: "Quais duas medidas reduzem o risco de ataques de salto de VLAN (VLAN hopping)? (Escolha duas.)",
    opcoes: [
      "Desativar a negociação de trunk (DTP) nas portas",
      "Trocar a VLAN nativa por uma VLAN sem uso",
      "Usar a VLAN 1 para a gerência",
      "Deixar as portas em dynamic desirable",
      "Deixar as portas sem uso na VLAN 1",
    ],
    certas: [0, 1],
    explicacao: "Sem DTP (switchport mode access ou switchport nonegotiate), o atacante não consegue negociar um trunk. Com a nativa em uma VLAN sem uso, o ataque de dupla marcação perde o efeito.",
  },
  {
    id: "srwe-24",
    curso: "SRWE",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Quais canais da faixa de 2,4 GHz não se sobrepõem?",
    opcoes: ["1, 6 e 11", "1, 5 e 9", "2, 7 e 12", "36, 40 e 44"],
    certas: [0],
    explicacao: "Os canais de 2,4 GHz têm 22 MHz de largura e ficam a 5 MHz uns dos outros. Só 1, 6 e 11 não se sobrepõem. Os canais 36, 40 e 44 são da faixa de 5 GHz.",
  },
  {
    id: "srwe-25",
    curso: "SRWE",
    topico: "Acesso à rede",
    tipo: "unica",
    enunciado: "Qual protocolo os APs leves (lightweight) usam para se comunicar com o controlador WLC?",
    opcoes: ["CAPWAP", "CDP", "RADIUS", "SNMP"],
    certas: [0],
    explicacao: "O CAPWAP cria túneis entre o AP e o WLC, para controle e para dados. O RADIUS autentica usuários, e o SNMP serve à gerência.",
  },
  {
    id: "srwe-26",
    curso: "SRWE",
    topico: "Fundamentos de segurança",
    tipo: "unica",
    enunciado: "Qual é a opção mais segura para a rede sem fio de uma empresa?",
    opcoes: [
      "WPA3-Enterprise, com autenticação 802.1X em um servidor RADIUS",
      "WPA2-Personal, com uma senha compartilhada",
      "WEP",
      "Rede aberta com filtro de MAC",
    ],
    certas: [0],
    explicacao: "No modo Enterprise, cada usuário se autentica com credenciais próprias no RADIUS. A senha compartilhada do modo Personal é mais fraca, o WEP é quebrado em minutos e o filtro de MAC é fácil de burlar.",
  },
  {
    id: "srwe-27",
    curso: "SRWE",
    topico: "Conectividade IP",
    tipo: "associar",
    enunciado: "Associe cada origem de rota à sua distância administrativa padrão.",
    alvos: ["0", "1", "110", "120"],
    pares: [
      ["Rede diretamente conectada", "0"],
      ["Rota estática", "1"],
      ["OSPF", "110"],
      ["RIP", "120"],
    ],
    explicacao: "Quanto menor a distância administrativa, mais confiável é a origem. Ela só desempata rotas para o mesmo prefixo vindas de origens diferentes; o prefixo mais longo vem antes.",
  },
  {
    id: "srwe-28",
    curso: "SRWE",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "R1 aprende 10.10.0.0/16 pelo OSPF. Qual comando cria uma rota estática flutuante, que só entra na tabela se a rota OSPF cair?",
    opcoes: [
      "ip route 10.10.0.0 255.255.0.0 172.16.1.2 130",
      "ip route 10.10.0.0 255.255.0.0 172.16.1.2 100",
      "ip route 10.10.0.0 255.255.0.0 172.16.1.2",
      "ip route 0.0.0.0 0.0.0.0 172.16.1.2",
    ],
    certas: [0],
    explicacao: "A rota flutuante precisa de distância administrativa maior que a da rota principal (OSPF = 110). Com 100 ou com o padrão 1, a estática venceria o OSPF e entraria sempre.",
  },
  {
    id: "srwe-29",
    curso: "SRWE",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "Qual comando configura uma rota padrão IPv4 apontando para o provedor em 209.165.200.1?",
    opcoes: [
      "ip route 0.0.0.0 0.0.0.0 209.165.200.1",
      "ip route 255.255.255.255 0.0.0.0 209.165.200.1",
      "ip route 0.0.0.0 255.255.255.255 209.165.200.1",
      "ipv6 route ::/0 209.165.200.1",
    ],
    certas: [0],
    explicacao: "A rota padrão é 0.0.0.0 com máscara 0.0.0.0 (/0): combina com qualquer destino e só é usada quando não há rota mais específica.",
  },
  {
    id: "srwe-30",
    curso: "SRWE",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "Qual comando configura uma rota padrão IPv6?",
    opcoes: [
      "ipv6 route ::/0 2001:db8:acad:1::1",
      "ipv6 route ::/128 2001:db8:acad:1::1",
      "ipv6 route ::1/0 2001:db8:acad:1::1",
      "ip route ::/0 2001:db8:acad:1::1",
    ],
    certas: [0],
    explicacao: "No IPv6, a rota padrão é ::/0. O comando é ipv6 route, e o roteador também precisa de ipv6 unicast-routing para encaminhar pacotes IPv6.",
  },
  {
    id: "srwe-31",
    curso: "SRWE",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "A rota estática para 192.168.30.0/24 está na configuração, mas não aparece na tabela de roteamento. Observe as saídas. Qual é a causa?",
    exibicao: `R1# show running-config | include ip route
ip route 192.168.30.0 255.255.255.0 10.0.0.6

R1# show running-config interface Serial0/1/0
interface Serial0/1/0
 ip address 10.0.0.1 255.255.255.252

R1# show ip route static
R1#`,
    opcoes: [
      "O próximo salto 10.0.0.6 não pertence a nenhuma rede conectada a R1.",
      "A distância administrativa da rota está errada.",
      "A máscara da rede de destino está errada.",
      "Rotas estáticas não aparecem no show ip route.",
    ],
    certas: [0],
    explicacao: "O /30 da serial tem só os hosts 10.0.0.1 e 10.0.0.2. Como R1 não alcança 10.0.0.6, a rota não é instalada. O próximo salto certo é 10.0.0.2, o vizinho do outro lado do link.",
  },
  {
    id: "srwe-32",
    curso: "SRWE",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "Uma rota estática foi configurada só com o endereço do próximo salto. O que o roteador precisa fazer para encaminhar um pacote por ela?",
    opcoes: [
      "Uma busca recursiva na tabela, para descobrir a interface de saída do próximo salto",
      "Uma consulta ARP para cada pacote enviado",
      "Uma consulta ao vizinho OSPF",
      "Nada: a interface de saída é escolhida ao acaso.",
    ],
    certas: [0],
    explicacao: "Com só o próximo salto, o roteador consulta a tabela de novo para saber por qual interface alcançá-lo. Ao informar a interface e o próximo salto juntos (rota totalmente especificada), essa busca extra não é necessária.",
  },
  {
    id: "srwe-33",
    curso: "SRWE",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Qual comando define o gateway padrão de um switch de camada 2, para que ele seja gerenciado a partir de outras redes?",
    opcoes: [
      "ip default-gateway 192.168.99.1",
      "ip route 0.0.0.0 0.0.0.0 192.168.99.1",
      "default-router 192.168.99.1",
      "ip gateway 192.168.99.1",
    ],
    certas: [0],
    explicacao: "Um switch de camada 2 não roteia, então usa o ip default-gateway, no modo global, para responder a quem está em outra rede. O default-router é um comando do pool DHCP.",
  },
  {
    id: "srwe-34",
    curso: "SRWE",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Onde se configura o endereço IP de gerência de um switch de camada 2?",
    opcoes: [
      "Em uma SVI, como interface vlan 99",
      "Em uma porta FastEthernet",
      "Na linha VTY",
      "Na linha de console",
    ],
    certas: [0],
    explicacao: "As portas físicas de um switch de camada 2 não recebem IP. O endereço de gerência fica em uma interface virtual da VLAN de gerência, que precisa estar ativa (no shutdown).",
  },
  {
    id: "srwe-35",
    curso: "SRWE",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Por padrão, quanto tempo uma entrada dinâmica fica na tabela MAC de um switch Cisco se o host não enviar mais nada?",
    opcoes: ["300 segundos", "30 segundos", "60 segundos", "1 hora"],
    certas: [0],
    explicacao: "O tempo de envelhecimento (aging) padrão é de 300 segundos, ou 5 minutos. A cada quadro recebido do host, o contador recomeça.",
  },
  {
    id: "srwe-36",
    curso: "SRWE",
    topico: "Acesso à rede",
    tipo: "multipla",
    enunciado: "Quais duas afirmações sobre o LLDP são verdadeiras? (Escolha duas.)",
    opcoes: [
      "É um padrão aberto, o IEEE 802.1AB.",
      "Permite descobrir vizinhos de fabricantes diferentes.",
      "É um protocolo proprietário da Cisco.",
      "Vem habilitado por padrão em todos os switches Cisco.",
      "Funciona na camada de rede.",
    ],
    certas: [0, 1],
    explicacao: "O LLDP é a alternativa aberta ao CDP e funciona na camada 2. Em muitos equipamentos Cisco, ele vem desligado e é habilitado com lldp run. O CDP, sim, vem ligado por padrão.",
  },
  {
    id: "srwe-37",
    curso: "SRWE",
    topico: "Acesso à rede",
    tipo: "unica",
    enunciado: "Qual versão do Spanning Tree, da Cisco, roda uma instância por VLAN e converge rapidamente?",
    opcoes: ["Rapid PVST+", "STP 802.1D", "MSTP", "PVST+"],
    certas: [0],
    explicacao: "O Rapid PVST+ é o RSTP (802.1w) com uma instância por VLAN. O PVST+ também tem uma instância por VLAN, mas usa a convergência lenta do 802.1D. O MSTP agrupa VLANs em instâncias.",
  },
  {
    id: "srwe-38",
    curso: "SRWE",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Os hosts IPv6 devem receber o endereço de um servidor DHCPv6 com estado. Qual flag precisa estar ativo nas mensagens RA do roteador?",
    opcoes: ["M (Managed) = 1", "M = 0 e O = 1", "M = 0 e O = 0", "As RAs não têm flags para isso."],
    certas: [0],
    explicacao: "O flag M = 1 manda o host pedir o endereço ao DHCPv6 com estado. No roteador, ele é ativado com ipv6 nd managed-config-flag na interface.",
  },
  {
    id: "srwe-39",
    curso: "SRWE",
    topico: "Acesso à rede",
    tipo: "associar",
    enunciado: "Associe cada descrição ao termo de redes sem fio.",
    alvos: ["SSID", "WLC", "AP autônomo", "RADIUS"],
    pares: [
      ["Nome que identifica a rede sem fio", "SSID"],
      ["Gerencia de forma centralizada vários APs", "WLC"],
      ["Configurado individualmente, sem controlador", "AP autônomo"],
      ["Autentica os usuários no modo Enterprise", "RADIUS"],
    ],
    explicacao: "Em redes pequenas, APs autônomos dão conta. Em redes grandes, um WLC configura todos os APs leves de uma vez. O RADIUS valida cada usuário no WPA2/WPA3-Enterprise.",
  },
  {
    id: "srwe-40",
    curso: "SRWE",
    topico: "Acesso à rede",
    tipo: "unica",
    enunciado: "O EtherChannel entre S1 e S2 não se forma. As portas de S2 estão em modo LACP passive. Observe a saída de S1. Qual é a causa provável?",
    exibicao: `S1# show etherchannel summary
Flags:  D - down        P - bundled in port-channel
        I - stand-alone s - suspended
        S - Layer2      U - in use

Group  Port-channel  Protocol    Ports
------+-------------+-----------+------------------
1      Po1(SD)         LACP      Fa0/1(I)  Fa0/2(I)`,
    opcoes: [
      "As portas de S1 também estão em modo passive.",
      "O LACP não funciona em portas FastEthernet.",
      "As portas de S1 estão em modo active.",
      "O EtherChannel exige quatro portas no mínimo.",
    ],
    certas: [0],
    explicacao: "As portas aparecem como I (stand-alone): não houve negociação. Com os dois lados em passive, ninguém inicia o LACP. Colocar S1 em active resolve.",
  },

  /* ---------------------------------------------------------------
     ENSA · Enterprise Networking, Security and Automation
     --------------------------------------------------------------- */
  {
    id: "ensa-01",
    curso: "ENSA",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "Sem o comando router-id, como o OSPFv2 escolhe o ID do roteador?",
    opcoes: [
      "O maior IPv4 de uma interface de loopback; sem loopback, o maior IPv4 de uma interface física ativa",
      "O menor IPv4 entre todas as interfaces",
      "O endereço MAC da primeira interface",
      "A maior prioridade OSPF configurada",
    ],
    certas: [0],
    explicacao: "A ordem é: router-id configurado, maior IP de loopback, maior IP de interface ativa. Por isso é comum criar uma loopback ou fixar o router-id, para o ID não mudar sozinho.",
  },
  {
    id: "ensa-02",
    curso: "ENSA",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "Qual é a distância administrativa padrão do OSPF?",
    opcoes: ["110", "90", "120", "1"],
    certas: [0],
    explicacao: "OSPF = 110, EIGRP interno = 90, RIP = 120 e rota estática = 1. Se duas origens ensinam o mesmo prefixo, vence a de menor distância administrativa.",
  },
  {
    id: "ensa-03",
    curso: "ENSA",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "Em uma rede multiacesso, como o OSPF elege o roteador designado (DR)?",
    opcoes: [
      "Maior prioridade de interface; em empate, maior router ID",
      "Menor router ID",
      "Maior endereço IP de loopback, sem olhar a prioridade",
      "O roteador com mais vizinhos",
    ],
    certas: [0],
    explicacao: "A prioridade padrão é 1 e vence a maior. Em empate, vence o maior router ID. A eleição não tem preempção: um roteador melhor que entra depois não toma o lugar do DR atual.",
  },
  {
    id: "ensa-04",
    curso: "ENSA",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "Qual prioridade OSPF, configurada em uma interface, impede que o roteador seja DR ou BDR naquele segmento?",
    opcoes: ["0", "1", "100", "255"],
    certas: [0],
    explicacao: "Com ip ospf priority 0, o roteador não participa da eleição. O padrão é 1 e o máximo é 255.",
  },
  {
    id: "ensa-05",
    curso: "ENSA",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "Com a largura de banda de referência padrão (100 Mb/s), qual é o custo OSPF de uma interface FastEthernet?",
    opcoes: ["1", "10", "100", "64"],
    certas: [0],
    explicacao: "Custo = 100 Mb/s ÷ largura de banda da interface. FastEthernet dá 1, e GigabitEthernet também dá 1, porque o custo não fica abaixo de 1. Por isso se ajusta o auto-cost reference-bandwidth em redes rápidas.",
  },
  {
    id: "ensa-06",
    curso: "ENSA",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "Quatro roteadores OSPF estão na mesma LAN. Observe os vizinhos de R1. Qual é o papel de R1 nesse segmento?",
    exibicao: `R1# show ip ospf neighbor
Neighbor ID   Pri  State           Dead Time  Address    Interface
2.2.2.2         1  FULL/DR         00:00:35   10.1.1.2   Gi0/0/0
3.3.3.3         1  FULL/BDR        00:00:33   10.1.1.3   Gi0/0/0
4.4.4.4         1  2WAY/DROTHER    00:00:31   10.1.1.4   Gi0/0/0`,
    opcoes: ["DROTHER", "DR", "BDR", "R1 não formou nenhuma adjacência."],
    certas: [0],
    explicacao: "O DR e o BDR já são outros roteadores. R1 forma adjacência completa (FULL) com eles e fica em 2WAY com o outro DROTHER, o que é normal: DROTHERs não trocam LSAs diretamente entre si.",
  },
  {
    id: "ensa-07",
    curso: "ENSA",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "R1 e R2 estão na mesma rede, mas não formam adjacência OSPF. Observe as saídas. Qual é a causa?",
    exibicao: `R1# show ip ospf interface g0/0/0 | include Timer
  Timer intervals configured, Hello 10, Dead 40, Wait 40, Retransmit 5

R2# show ip ospf interface g0/0/0 | include Timer
  Timer intervals configured, Hello 5, Dead 20, Wait 20, Retransmit 5`,
    opcoes: [
      "Os intervalos de Hello e Dead são diferentes.",
      "Os router IDs são diferentes.",
      "As prioridades OSPF são iguais.",
      "Os custos das interfaces são diferentes.",
    ],
    certas: [0],
    explicacao: "Para virar vizinhos, os roteadores precisam ter os mesmos timers de Hello e Dead, a mesma área, a mesma sub-rede e a mesma autenticação. Router IDs diferentes são obrigatórios, e custos diferentes não impedem a adjacência.",
  },
  {
    id: "ensa-08",
    curso: "ENSA",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "Qual comando impede o envio de Hellos OSPF para a LAN dos usuários, mas mantém essa rede anunciada aos outros roteadores?",
    opcoes: [
      "passive-interface GigabitEthernet0/0/1",
      "no network 192.168.1.0 0.0.0.255 area 0",
      "shutdown na interface GigabitEthernet0/0/1",
      "ip ospf priority 0 na interface GigabitEthernet0/0/1",
    ],
    certas: [0],
    explicacao: "A interface passiva continua anunciada, mas não envia Hellos. Isso economiza recursos e impede que um dispositivo na LAN dos usuários forme adjacência e injete rotas falsas.",
  },
  {
    id: "ensa-09",
    curso: "ENSA",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "O roteador de borda tem uma rota padrão estática para o provedor. Qual comando faz o OSPF anunciar essa rota padrão aos outros roteadores?",
    opcoes: [
      "default-information originate",
      "redistribute connected",
      "network 0.0.0.0 255.255.255.255 area 0",
      "ip default-gateway",
    ],
    certas: [0],
    explicacao: "O default-information originate, no modo router ospf, propaga a rota padrão que o roteador de borda tem. O network 0.0.0.0 255.255.255.255 apenas ativaria o OSPF em todas as interfaces.",
  },
  {
    id: "ensa-10",
    curso: "ENSA",
    topico: "Conectividade IP",
    tipo: "unica",
    enunciado: "Qual comando ativa o OSPF somente na interface com endereço 10.1.1.1, na área 0?",
    opcoes: [
      "network 10.1.1.1 0.0.0.0 area 0",
      "network 10.1.1.0 0.0.0.255 area 1",
      "network 10.1.1.1 area 0",
      "ospf network 10.1.1.1 area 0",
    ],
    certas: [0],
    explicacao: "A máscara curinga 0.0.0.0 exige correspondência exata do endereço, então só aquela interface entra no OSPF. Outra forma é usar ip ospf 1 area 0 dentro da própria interface.",
  },
  {
    id: "ensa-11",
    curso: "ENSA",
    topico: "Fundamentos de segurança",
    tipo: "unica",
    enunciado: "Qual máscara curinga corresponde a todos os endereços da sub-rede 192.168.10.0/26?",
    opcoes: ["0.0.0.63", "0.0.0.64", "255.255.255.192", "0.0.0.255"],
    certas: [0],
    explicacao: "A curinga é o inverso da máscara: 255.255.255.255 − 255.255.255.192 = 0.0.0.63. Os bits 0 precisam combinar, e os bits 1 podem ter qualquer valor.",
  },
  {
    id: "ensa-12",
    curso: "ENSA",
    topico: "Fundamentos de segurança",
    tipo: "unica",
    enunciado: "O que acontece com um pacote que não combina com nenhuma ACE de uma ACL aplicada a uma interface?",
    opcoes: [
      "É descartado pelo deny implícito no final da ACL.",
      "É permitido, porque nenhuma regra o bloqueou.",
      "É enviado para a CPU analisar.",
      "É registrado no log e depois permitido.",
    ],
    certas: [0],
    explicacao: "Toda ACL termina com um deny any implícito, que não aparece na configuração. Por isso, uma ACL com só regras deny bloqueia tudo; costuma-se terminar com permit any quando a intenção é bloquear só algumas coisas.",
  },
  {
    id: "ensa-13",
    curso: "ENSA",
    topico: "Fundamentos de segurança",
    tipo: "unica",
    enunciado: "Onde se recomenda aplicar uma ACL padrão (standard)?",
    opcoes: [
      "O mais perto possível do destino",
      "O mais perto possível da origem",
      "Em todas as interfaces do caminho",
      "Somente na interface WAN",
    ],
    certas: [0],
    explicacao: "A ACL padrão filtra só pela origem. Perto da origem, ela bloquearia o acesso a todos os destinos. A ACL estendida, que filtra com mais detalhes, fica perto da origem.",
  },
  {
    id: "ensa-14",
    curso: "ENSA",
    topico: "Fundamentos de segurança",
    tipo: "unica",
    enunciado: "O objetivo é bloquear só o host 192.168.10.5 e permitir o resto da rede 192.168.10.0/24. Observe a ACL. Qual é o problema?",
    exibicao: `access-list 10 permit 192.168.10.0 0.0.0.255
access-list 10 deny host 192.168.10.5`,
    opcoes: [
      "A ordem: o permit vem antes, então o host .5 é permitido.",
      "A máscara curinga do permit está errada.",
      "O comando deny host não existe em ACL padrão.",
      "Faltou o deny any no final.",
    ],
    certas: [0],
    explicacao: "As ACEs são lidas de cima para baixo, e a primeira que combina decide. O .5 combina com o permit da primeira linha. O deny host precisa vir antes do permit da rede.",
  },
  {
    id: "ensa-15",
    curso: "ENSA",
    topico: "Fundamentos de segurança",
    tipo: "unica",
    enunciado: "Qual ACE bloqueia o acesso HTTP da rede 192.168.10.0/24 ao servidor 10.1.1.10?",
    opcoes: [
      "access-list 110 deny tcp 192.168.10.0 0.0.0.255 host 10.1.1.10 eq 80",
      "access-list 110 deny udp 192.168.10.0 0.0.0.255 host 10.1.1.10 eq 80",
      "access-list 110 deny tcp host 10.1.1.10 192.168.10.0 0.0.0.255 eq 80",
      "access-list 10 deny 192.168.10.0 0.0.0.255 eq 80",
    ],
    certas: [0],
    explicacao: "O HTTP usa TCP 80 no destino. A ordem é protocolo, origem, destino e porta. A terceira opção inverte origem e destino, e a última é uma ACL padrão, que não filtra porta.",
  },
  {
    id: "ensa-16",
    curso: "ENSA",
    topico: "Fundamentos de segurança",
    tipo: "multipla",
    enunciado: "Quais duas afirmações sobre ACLs IPv4 são verdadeiras? (Escolha duas.)",
    opcoes: [
      "Cabe uma ACL por interface, por sentido e por protocolo.",
      "As ACEs são verificadas de cima para baixo, e a primeira que combina decide.",
      "A ACL padrão filtra por número de porta.",
      "Uma ACL vazia aplicada a uma interface bloqueia todo o tráfego.",
      "A ACL estendida filtra só pelo endereço de destino.",
    ],
    certas: [0, 1],
    explicacao: "É uma ACL por interface, por sentido (in ou out) e por protocolo (IPv4 ou IPv6). Uma ACL vazia, sem nenhuma ACE, não bloqueia nada. A estendida filtra origem, destino, protocolo e portas.",
  },
  {
    id: "ensa-17",
    curso: "ENSA",
    topico: "Serviços IP",
    tipo: "associar",
    enunciado: "Associe cada descrição ao termo do NAT.",
    alvos: ["Inside local", "Inside global", "Outside global", "Outside local"],
    pares: [
      ["Endereço privado do host interno", "Inside local"],
      ["Endereço público que representa o host interno na internet", "Inside global"],
      ["Endereço público real do servidor externo", "Outside global"],
      ["Endereço do host externo como visto pela rede interna", "Outside local"],
    ],
    explicacao: "Inside e outside dizem de quem é o endereço; local e global dizem de onde ele é visto. Na maioria das redes, o outside local e o outside global são iguais.",
  },
  {
    id: "ensa-18",
    curso: "ENSA",
    topico: "Serviços IP",
    tipo: "unica",
    enunciado: "Qual tipo de NAT permite que muitos hosts internos usem um único endereço público, separando as conexões pelas portas?",
    opcoes: ["PAT (NAT com overload)", "NAT estático", "NAT dinâmico com pool", "NAT64"],
    certas: [0],
    explicacao: "O PAT usa o número de porta para saber a qual host interno pertence cada conexão. É o NAT da maioria das casas e empresas. O NAT estático e o dinâmico usam um IP público por host.",
  },
  {
    id: "ensa-19",
    curso: "ENSA",
    topico: "Serviços IP",
    tipo: "unica",
    enunciado: "Os hosts internos não acessam a internet. G0/0/0 fica na LAN e G0/0/1 vai para o provedor. Observe a configuração. O que falta?",
    exibicao: `R1(config)# access-list 1 permit 192.168.0.0 0.0.255.255
R1(config)# ip nat inside source list 1 interface g0/0/1 overload
R1(config)# interface g0/0/0
R1(config-if)# ip nat inside`,
    opcoes: [
      "O comando ip nat outside na interface G0/0/1",
      "Um ip nat pool com endereços públicos",
      "Um permit any no final da ACL 1",
      "Uma tradução estática para cada host",
    ],
    certas: [0],
    explicacao: "O NAT só traduz o tráfego que passa de uma interface inside para uma outside. Sem ip nat outside na interface do provedor, nada é traduzido. Com overload na interface, o pool é dispensável.",
  },
  {
    id: "ensa-20",
    curso: "ENSA",
    topico: "Serviços IP",
    tipo: "unica",
    enunciado: "Por que usar NAT estático para um servidor web da rede interna?",
    opcoes: [
      "Para que ele seja acessado da internet por um endereço público fixo",
      "Para economizar endereços públicos",
      "Para esconder todos os hosts atrás de um único IP",
      "Para acelerar o roteamento",
    ],
    certas: [0],
    explicacao: "O NAT estático liga um IP privado a um IP público, sempre o mesmo. Assim, conexões que começam lá fora conseguem chegar ao servidor. Economizar endereços é a vantagem do PAT.",
  },
  {
    id: "ensa-21",
    curso: "ENSA",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Qual tecnologia WAN de provedor encaminha os pacotes por rótulos (labels), e não pelo endereço IP de destino?",
    opcoes: ["MPLS", "DSL", "Metro Ethernet", "Cabo (DOCSIS)"],
    certas: [0],
    explicacao: "No MPLS, o roteador de entrada da rede do provedor coloca um rótulo, e os roteadores do meio encaminham olhando só esse rótulo. O provedor transporta vários tipos de tráfego e de cliente na mesma infraestrutura.",
  },
  {
    id: "ensa-22",
    curso: "ENSA",
    topico: "Fundamentos de segurança",
    tipo: "unica",
    enunciado: "Qual tipo de VPN liga duas filiais de forma permanente, sem que os usuários precisem instalar um cliente de VPN?",
    opcoes: [
      "VPN site a site",
      "VPN de acesso remoto",
      "VPN SSL acessada pelo navegador",
      "Um túnel GRE sem criptografia",
    ],
    certas: [0],
    explicacao: "Na VPN site a site, os roteadores ou firewalls das duas pontas montam o túnel, e os hosts nem percebem. A VPN de acesso remoto é para o usuário que trabalha de fora, com cliente ou navegador.",
  },
  {
    id: "ensa-23",
    curso: "ENSA",
    topico: "Fundamentos de segurança",
    tipo: "unica",
    enunciado: "Por que é comum combinar GRE com IPsec entre duas filiais?",
    opcoes: [
      "O GRE transporta multicast, como os Hellos do OSPF, e o IPsec cifra o tráfego.",
      "O GRE cifra os dados, e o IPsec cria o túnel.",
      "O IPsec transporta multicast, e o GRE autentica os roteadores.",
      "Os dois juntos dispensam o roteamento.",
    ],
    certas: [0],
    explicacao: "O GRE encapsula quase qualquer protocolo, inclusive multicast, mas não cifra nada. O IPsec cifra, mas, sozinho, não transporta multicast. Juntos, permitem rodar OSPF por um túnel seguro.",
  },
  {
    id: "ensa-24",
    curso: "ENSA",
    topico: "Fundamentos de segurança",
    tipo: "multipla",
    enunciado: "Quais dois serviços o IPsec oferece? (Escolha dois.)",
    opcoes: [
      "Confidencialidade, por criptografia",
      "Integridade dos dados",
      "Balanceamento de carga",
      "Atribuição dinâmica de endereços",
      "Compressão de voz",
    ],
    certas: [0, 1],
    explicacao: "O IPsec oferece confidencialidade (AES), integridade (SHA), autenticação da origem (chaves ou certificados) e proteção contra repetição. Balanceamento e endereçamento não são funções dele.",
  },
  {
    id: "ensa-25",
    curso: "ENSA",
    topico: "Serviços IP",
    tipo: "unica",
    enunciado: "Qual é o atraso máximo recomendado, em um sentido, para o tráfego de voz?",
    opcoes: ["150 ms", "400 ms", "30 ms", "1 segundo"],
    certas: [0],
    explicacao: "Para voz, recomenda-se até 150 ms de atraso em um sentido, até 30 ms de jitter e até 1% de perda. Acima disso, a conversa fica truncada.",
  },
  {
    id: "ensa-26",
    curso: "ENSA",
    topico: "Serviços IP",
    tipo: "unica",
    enunciado: "Qual marcação DSCP é recomendada para o tráfego de voz?",
    opcoes: ["EF (46)", "AF11", "CS0", "AF41"],
    certas: [0],
    explicacao: "EF (Expedited Forwarding, 46) indica tráfego que precisa de pouco atraso e pouca perda, como a voz. AF41 costuma marcar vídeo, e CS0 é o melhor esforço (best effort).",
  },
  {
    id: "ensa-27",
    curso: "ENSA",
    topico: "Serviços IP",
    tipo: "associar",
    enunciado: "Associe cada ação à ferramenta de QoS.",
    alvos: ["Classificação", "Marcação", "Enfileiramento", "Policiamento"],
    pares: [
      ["Identificar a que tipo pertence o tráfego", "Classificação"],
      ["Gravar um valor, como o DSCP, no cabeçalho", "Marcação"],
      ["Organizar os pacotes em filas por prioridade", "Enfileiramento"],
      ["Descartar o tráfego que passa do limite contratado", "Policiamento"],
    ],
    explicacao: "Primeiro se classifica e marca, de preferência perto da origem. Depois, nos pontos de congestionamento, o enfileiramento dá prioridade. O policiamento descarta o excesso; o shaping, em vez disso, o atrasa.",
  },
  {
    id: "ensa-28",
    curso: "ENSA",
    topico: "Serviços IP",
    tipo: "unica",
    enunciado: "Qual mensagem SNMP o agente envia por conta própria para avisar o gerente sobre um evento, como uma interface que caiu?",
    opcoes: ["Trap", "Get", "Set", "GetNext"],
    certas: [0],
    explicacao: "Get, GetNext e Set partem do gerente para ler ou alterar valores. A trap (ou o inform, que exige confirmação) parte do agente, sem ninguém pedir.",
  },
  {
    id: "ensa-29",
    curso: "ENSA",
    topico: "Serviços IP",
    tipo: "unica",
    enunciado: "Qual nível de severidade do syslog é o mais crítico?",
    opcoes: ["0 · Emergência", "7 · Depuração", "3 · Erro", "5 · Notificação"],
    certas: [0],
    explicacao: "Quanto menor o número, mais grave: de 0 (emergência) a 7 (depuração). Ao definir um nível, como logging trap 4, o dispositivo envia aquele nível e todos os mais graves.",
  },
  {
    id: "ensa-30",
    curso: "ENSA",
    topico: "Serviços IP",
    tipo: "associar",
    enunciado: "Associe cada severidade do syslog ao seu número.",
    alvos: ["0", "3", "4", "7"],
    pares: [
      ["Emergência (sistema inutilizável)", "0"],
      ["Erro", "3"],
      ["Aviso (warning)", "4"],
      ["Depuração (debugging)", "7"],
    ],
    explicacao: "A escala completa: 0 emergência, 1 alerta, 2 crítico, 3 erro, 4 aviso, 5 notificação, 6 informativo e 7 depuração.",
  },
  {
    id: "ensa-31",
    curso: "ENSA",
    topico: "Serviços IP",
    tipo: "unica",
    enunciado: "Por que sincronizar o relógio dos roteadores e switches com NTP?",
    opcoes: [
      "Para que os logs tenham horários corretos e comparáveis entre os dispositivos",
      "Para acelerar o roteamento",
      "Para distribuir endereços IP",
      "Para cifrar as senhas",
    ],
    certas: [0],
    explicacao: "Ao investigar um incidente, é preciso juntar logs de vários dispositivos. Sem horário sincronizado, não dá para saber a ordem dos eventos. Certificados digitais também dependem da hora certa.",
  },
  {
    id: "ensa-32",
    curso: "ENSA",
    topico: "Serviços IP",
    tipo: "unica",
    enunciado: "Um servidor NTP está ligado diretamente a um relógio atômico. Qual é o stratum desse servidor?",
    opcoes: ["1", "0", "2", "16"],
    certas: [0],
    explicacao: "O relógio de referência é o stratum 0, e o servidor ligado a ele é o stratum 1. Cada salto soma 1. O stratum 16 indica um relógio não sincronizado.",
  },
  {
    id: "ensa-33",
    curso: "ENSA",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "No modelo hierárquico de três camadas, qual camada conecta os usuários finais e costuma aplicar o port security?",
    opcoes: ["Acesso", "Distribuição", "Núcleo", "Aplicação"],
    certas: [0],
    explicacao: "A camada de acesso liga PCs, telefones e APs. A distribuição agrega os switches de acesso e aplica políticas, como ACLs e roteamento entre VLANs. O núcleo transporta rapidamente o tráfego entre os blocos.",
  },
  {
    id: "ensa-34",
    curso: "ENSA",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "O que é um projeto de núcleo colapsado (collapsed core)?",
    opcoes: [
      "Um projeto em que as camadas de distribuição e núcleo são combinadas",
      "Um projeto sem camada de acesso",
      "Um núcleo que falhou e precisa ser substituído",
      "Um projeto em que cada switch de acesso liga direto à internet",
    ],
    certas: [0],
    explicacao: "Em redes de porte médio, um par de switches faz o papel de distribuição e de núcleo ao mesmo tempo. O projeto fica mais barato e simples, mas escala menos que o de três camadas.",
  },
  {
    id: "ensa-35",
    curso: "ENSA",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Um técnico investiga uma falha começando pelos cabos e pelas luzes das portas e sobe, camada por camada, até a aplicação. Qual método é esse?",
    opcoes: ["De baixo para cima (bottom-up)", "De cima para baixo (top-down)", "Dividir para conquistar", "Seguir o caminho"],
    certas: [0],
    explicacao: "O bottom-up começa na camada física e é bom quando a falha parece ser de hardware ou cabeamento. O top-down começa na aplicação, e o dividir para conquistar começa por uma camada do meio, como um ping.",
  },
  {
    id: "ensa-36",
    curso: "ENSA",
    topico: "Fundamentos de rede",
    tipo: "unica",
    enunciado: "Qual tipo de hipervisor roda diretamente no hardware, sem um sistema operacional hospedeiro?",
    opcoes: ["Tipo 1 (bare metal)", "Tipo 2 (hospedado)", "Contêiner", "Emulador de terminal"],
    certas: [0],
    explicacao: "O tipo 1, como VMware ESXi e Hyper-V, é usado em data centers. O tipo 2, como VirtualBox e VMware Workstation, roda sobre um sistema operacional, bom para laboratório.",
  },
  {
    id: "ensa-37",
    curso: "ENSA",
    topico: "Automação e programabilidade",
    tipo: "unica",
    enunciado: "Em uma rede definida por software (SDN), o que sai dos dispositivos e fica centralizado no controlador?",
    opcoes: ["O plano de controle", "O plano de dados", "A camada física", "A tabela MAC"],
    certas: [0],
    explicacao: "O plano de controle decide para onde o tráfego vai (rotas e políticas), e o plano de dados encaminha os pacotes. Na SDN, o controlador concentra as decisões, e os dispositivos só encaminham.",
  },
  {
    id: "ensa-38",
    curso: "ENSA",
    topico: "Automação e programabilidade",
    tipo: "associar",
    enunciado: "Associe cada operação CRUD ao método HTTP mais usado em uma API REST.",
    alvos: ["POST", "GET", "PUT", "DELETE"],
    pares: [
      ["Criar (Create)", "POST"],
      ["Ler (Read)", "GET"],
      ["Atualizar (Update)", "PUT"],
      ["Apagar (Delete)", "DELETE"],
    ],
    explicacao: "As APIs REST usam os métodos do HTTP para agir sobre recursos. Para atualizar, também se usa o PATCH, que altera só parte do recurso.",
  },
  {
    id: "ensa-39",
    curso: "ENSA",
    topico: "Automação e programabilidade",
    tipo: "unica",
    enunciado: "Qual API o controlador SDN oferece para que as aplicações peçam serviços à rede?",
    opcoes: ["Northbound", "Southbound", "OpenFlow", "NETCONF"],
    certas: [0],
    explicacao: "A northbound fica acima do controlador, voltada às aplicações, geralmente REST. A southbound fica abaixo, voltada aos dispositivos; OpenFlow e NETCONF são exemplos de southbound.",
  },
  {
    id: "ensa-40",
    curso: "ENSA",
    topico: "Automação e programabilidade",
    tipo: "unica",
    enunciado: "Uma API devolveu os dados abaixo. Qual é o tipo de dado do valor de \"enabled\"?",
    exibicao: `{
  "interface": {
    "name": "GigabitEthernet1",
    "enabled": true,
    "ipv4": {
      "address": "10.1.1.1",
      "mask": "255.255.255.0"
    }
  }
}`,
    opcoes: ["Booleano", "Texto (string)", "Número", "Lista (array)"],
    certas: [0],
    explicacao: "true e false, sem aspas, são booleanos. Entre aspas, seriam textos. Os pares chave–valor ficam entre chaves (objetos), e as listas, entre colchetes.",
  },
  {
    id: "ensa-41",
    curso: "ENSA",
    topico: "Automação e programabilidade",
    tipo: "unica",
    enunciado: "Qual ferramenta de gerência de configuração funciona sem agente nos dispositivos e usa playbooks em YAML?",
    opcoes: ["Ansible", "Puppet", "Chef", "SNMP"],
    certas: [0],
    explicacao: "O Ansible se conecta por SSH (ou por APIs) e executa playbooks escritos em YAML. Puppet e Chef tradicionalmente usam agentes instalados nos dispositivos gerenciados.",
  },
  {
    id: "ensa-42",
    curso: "ENSA",
    topico: "Automação e programabilidade",
    tipo: "unica",
    enunciado: "Uma chamada a uma API REST devolve o código de status 404. O que isso significa?",
    opcoes: [
      "O recurso pedido não foi encontrado.",
      "A requisição deu certo.",
      "O usuário não está autenticado.",
      "Houve um erro interno no servidor.",
    ],
    certas: [0],
    explicacao: "Os códigos 2xx indicam sucesso (200 OK, 201 Created). Os 4xx são erros do cliente (401 não autenticado, 403 proibido, 404 não encontrado). Os 5xx são erros do servidor (500).",
  },
];
